# 误差反向传播法

In [2]:
import numpy as np

In [9]:
X = np.random.rand(1, 2)
W = np.random.rand(2, 3)
B = np.random.rand(3)

X.shape, W.shape, B.shape

((1, 2), (2, 3), (3,))

In [11]:
Y = np.dot(X, W) + B
Y

array([[0.52625109, 0.77445934, 1.09960401]])

In [4]:
X_dot_W = np.array([[0, 0, 0], [10, 10, 10]])
B = np.array([1, 2, 3])

X_dot_W + B

array([[ 1,  2,  3],
       [11, 12, 13]])

In [11]:
X = np.random.rand(2, 3)
W = np.random.rand(3, 3)
B = np.random.rand(1, 3)
X, W, B

(array([[0.18491797, 0.91083705, 0.35278159],
        [0.10039615, 0.95147113, 0.801176  ]]),
 array([[0.73616204, 0.38218828, 0.12655768],
        [0.59143032, 0.13245808, 0.40328366],
        [0.06032631, 0.26329406, 0.44806377]]),
 array([[0.13824877, 0.19380135, 0.87116758]]))

In [12]:
np.dot(X, W)

array([[0.69610825, 0.28420651, 0.54879714],
       [0.68496871, 0.37534516, 0.7553966 ]])

In [13]:
np.dot(X, W) + B

array([[0.83435702, 0.47800785, 1.41996471],
       [0.82321747, 0.5691465 , 1.62656418]])

In [6]:
import sys
import numpy as np
sys.path.append('common')
from common.layer import SoftmaxWithLoss

In [4]:
swl = SoftmaxWithLoss()

In [19]:
X = np.random.rand(5, 3)
t = np.array([[0, 1, 0],
              [1, 0, 0],
              [1, 0, 0],
              [0, 0, 1],
              [0, 1, 0]])

In [20]:
swl.forward(X, t)

1.0518713356873137

In [21]:
swl.backward(1)

array([[ 0.05380656, -0.12487296,  0.0710664 ],
       [-0.14856767,  0.10194672,  0.04662094],
       [-0.11448457,  0.0467257 ,  0.06775888],
       [ 0.08934796,  0.03511442, -0.12446238],
       [ 0.07723764, -0.1333501 ,  0.05611246]])

In [22]:
from common.function import softmax

In [25]:
(softmax(X) - t)/5

array([[ 0.05380656, -0.12487296,  0.0710664 ],
       [-0.14856767,  0.10194672,  0.04662094],
       [-0.11448457,  0.0467257 ,  0.06775888],
       [ 0.08934796,  0.03511442, -0.12446238],
       [ 0.07723764, -0.1333501 ,  0.05611246]])

In [26]:
(softmax(X) - t)

array([[ 0.26903281, -0.6243648 ,  0.35533199],
       [-0.74283833,  0.50973361,  0.23310472],
       [-0.57242286,  0.23362849,  0.33879438],
       [ 0.4467398 ,  0.17557211, -0.62231192],
       [ 0.3861882 , -0.6667505 ,  0.2805623 ]])

In [28]:
softmax(X) - t

array([[ 0.26903281, -0.6243648 ,  0.35533199],
       [-0.74283833,  0.50973361,  0.23310472],
       [-0.57242286,  0.23362849,  0.33879438],
       [ 0.4467398 ,  0.17557211, -0.62231192],
       [ 0.3861882 , -0.6667505 ,  0.2805623 ]])

In [29]:
t

array([[0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])