In [1]:
import numpy as np

In [2]:
test = 100 * np.round(np.random.randn(20, 4, 4, 3), 2)

In [3]:
test

array([[[[ -47.,  -20.,  -66.],
         [  -5.,  -60.,   36.],
         [ -25., -117.,   14.],
         [ -62.,   63.,   43.]],

        [[ -84., -213.,  -61.],
         [ 125., -117.,   37.],
         [ 170., -104.,   12.],
         [  24.,  -63.,  -67.]],

        [[  18., -109.,  137.],
         [  69.,  -86.,    2.],
         [ 143.,    1.,   77.],
         [ -50., -124.,  -20.]],

        [[ 132.,  149.,  -99.],
         [ 122.,   90.,  -40.],
         [   6.,  -70.,  -84.],
         [ -18.,   -9.,   85.]]],


       [[[ -86.,   42.,  -93.],
         [ -24.,   23.,   35.],
         [ -44.,  129., -193.],
         [-108.,   47.,  -38.]],

        [[ 190.,  -14., -181.],
         [ -40.,    3.,   18.],
         [   2.,   32.,   50.],
         [-139.,  131.,   33.]],

        [[ -42., -152.,   27.],
         [ 133.,  147., -162.],
         [  24.,  -61.,  -54.],
         [ -42., -155.,  -36.]],

        [[  30.,  -11., -181.],
         [   2., -131.,  -31.],
         [  75.,   33., 

In [4]:
test = 100 * np.round(np.random.randn(20, 3, 4, 4), 2)

In [5]:
test

array([[[[-164.,  -53.,   26., -162.],
         [   9.,  -59.,  -85.,   83.],
         [  44.,  103.,  169.,  203.],
         [  57.,  209.,  -16.,  -24.]],

        [[ -87.,   61.,  -40.,  -51.],
         [-167.,  -23., -245.,   33.],
         [ -31.,  -37.,   13.,  152.],
         [ 107., -109.,  -27.,   64.]],

        [[ -32., -107., -126.,  -65.],
         [  83.,   97.,   13.,  139.],
         [ -57.,  111.,  -50., -165.],
         [  25.,  246.,  -36., -106.]]],


       [[[ -42.,   62.,   17., -111.],
         [  47.,   69., -110.,  104.],
         [  37.,   91.,  128.,   34.],
         [  43.,   85.,  272.,   15.]],

        [[ 100.,  -75., -108.,  -48.],
         [ -50., -101.,   12.,  -27.],
         [  30.,  182.,  -45.,  -17.],
         [ 123., -154.,   33.,   27.]],

        [[  82.,  -97.,  168.,  -26.],
         [ -20.,   32.,  -89.,   76.],
         [ -70.,  -84.,  127.,   23.],
         [ 118.,  -91.,  -71., -197.]]],


       [[[  78.,   64., -107.,  -92.],
         

In [6]:
img = np.pad(test, [(0, 0), (0, 0), (1, 1), (1, 1)], 'constant')

In [7]:
img

array([[[[   0.,    0.,    0.,    0.,    0.,    0.],
         [   0., -164.,  -53.,   26., -162.,    0.],
         [   0.,    9.,  -59.,  -85.,   83.,    0.],
         [   0.,   44.,  103.,  169.,  203.,    0.],
         [   0.,   57.,  209.,  -16.,  -24.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.]],

        [[   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,  -87.,   61.,  -40.,  -51.,    0.],
         [   0., -167.,  -23., -245.,   33.,    0.],
         [   0.,  -31.,  -37.,   13.,  152.,    0.],
         [   0.,  107., -109.,  -27.,   64.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.]],

        [[   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,  -32., -107., -126.,  -65.,    0.],
         [   0.,   83.,   97.,   13.,  139.,    0.],
         [   0.,  -57.,  111.,  -50., -165.,    0.],
         [   0.,   25.,  246.,  -36., -106.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.]]],


       [[[   0.,    0.,    0.,    0., 

In [8]:
import sys, os

In [9]:
sys.path.append(os.pardir)

In [10]:
from common.util import im2col

In [16]:
x1 = np.arange(3*25).reshape(1, 3, 5, 5)
x1

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]],

        [[25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]],

        [[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74]]]])

In [19]:
col1 = im2col(x1, 4, 4, stride=1, pad=0)

In [20]:
col1.shape

(4, 48)

In [14]:
col1

array([[ 0.,  1.,  2.,  4.,  5.,  6.,  8.,  9., 10., 16., 17., 18., 20.,
        21., 22., 24., 25., 26., 32., 33., 34., 36., 37., 38., 40., 41.,
        42.],
       [ 1.,  2.,  3.,  5.,  6.,  7.,  9., 10., 11., 17., 18., 19., 21.,
        22., 23., 25., 26., 27., 33., 34., 35., 37., 38., 39., 41., 42.,
        43.],
       [ 4.,  5.,  6.,  8.,  9., 10., 12., 13., 14., 20., 21., 22., 24.,
        25., 26., 28., 29., 30., 36., 37., 38., 40., 41., 42., 44., 45.,
        46.],
       [ 5.,  6.,  7.,  9., 10., 11., 13., 14., 15., 21., 22., 23., 25.,
        26., 27., 29., 30., 31., 37., 38., 39., 41., 42., 43., 45., 46.,
        47.]])