In [1]:
import numpy as np

In [6]:
test = 100 * np.round(np.random.randn(20, 4, 4, 3), 2)

In [7]:
test

array([[[[  42.,  116.,   67.],
         [  96.,  -94.,    1.],
         [ -47., -141.,  105.],
         [  85.,  158.,   11.]],

        [[  85.,   51., -118.],
         [  97.,  -91.,  -55.],
         [  60.,  133.,  128.],
         [ -42.,  -55.,   83.]],

        [[ 115.,  -28.,  -72.],
         [ -24.,   71.,  119.],
         [ 110.,   29.,   57.],
         [ -49.,  110.,   31.]],

        [[ 100.,  -89., -164.],
         [  31.,  -70.,  -86.],
         [  23.,   35.,  -39.],
         [-191.,  139.,   41.]]],


       [[[  64.,  -97.,   89.],
         [ 137., -175.,   64.],
         [ -82.,  -92.,   -6.],
         [  13.,  -96.,  163.]],

        [[  13.,   66., -135.],
         [  78.,  -55.,  -48.],
         [  86., -164.,  -40.],
         [  59., -225.,   83.]],

        [[ -51.,   62.,   -7.],
         [  95.,   -1.,  -96.],
         [   3., -159.,   11.],
         [  13.,  -82., -133.]],

        [[ -28.,  159.,   60.],
         [  89.,  135.,  170.],
         [   3., -128., 

In [8]:
test = 100 * np.round(np.random.randn(20, 3, 4, 4), 2)

In [9]:
test

array([[[[ -27.,  272.,  151.,  -92.],
         [ -27.,  118.,   -3.,  -30.],
         [  -3.,  -10.,  152.,  -40.],
         [ -68.,  115., -139.,  124.]],

        [[-111.,  -92.,  -18., -169.],
         [-133.,   64., -118., -124.],
         [   6.,  -84.,    7., -115.],
         [-111.,  -27.,   -2.,  -73.]],

        [[ 211.,  123.,   34.,  -90.],
         [ -71.,   15.,  -78.,  -93.],
         [ 155.,  -25., -113.,  -36.],
         [  34.,    1., -122.,  180.]]],


       [[[ 129.,  -12.,  -10.,   46.],
         [ 110.,   76.,  -80.,   -8.],
         [ 113.,   18.,  110.,   18.],
         [  55., -121.,  -76.,  -31.]],

        [[ 143., -123.,  -51.,  118.],
         [  10.,   71.,  -65.,  228.],
         [ -93., -230.,  -97.,    6.],
         [  62.,   60., -178.,   -8.]],

        [[  -8.,   62.,   59.,  -19.],
         [ 109.,  214.,  -10.,   86.],
         [-163.,  151.,  -78., -162.],
         [  11.,  -27.,  116.,    0.]]],


       [[[ 145.,  112.,   74.,  -11.],
         

In [12]:
img = np.pad(test, [(0, 0), (0, 0), (1, 1), (1, 1)], 'constant')

In [13]:
img

array([[[[   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,  -27.,  272.,  151.,  -92.,    0.],
         [   0.,  -27.,  118.,   -3.,  -30.,    0.],
         [   0.,   -3.,  -10.,  152.,  -40.,    0.],
         [   0.,  -68.,  115., -139.,  124.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.]],

        [[   0.,    0.,    0.,    0.,    0.,    0.],
         [   0., -111.,  -92.,  -18., -169.,    0.],
         [   0., -133.,   64., -118., -124.,    0.],
         [   0.,    6.,  -84.,    7., -115.,    0.],
         [   0., -111.,  -27.,   -2.,  -73.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.]],

        [[   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,  211.,  123.,   34.,  -90.,    0.],
         [   0.,  -71.,   15.,  -78.,  -93.,    0.],
         [   0.,  155.,  -25., -113.,  -36.,    0.],
         [   0.,   34.,    1., -122.,  180.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.]]],


       [[[   0.,    0.,    0.,    0., 

In [14]:
import sys, os

In [15]:
sys.path.append(os.pardir)

In [16]:
from common.util import im2col

In [29]:
x1 = np.arange(3*16).reshape(1, 3, 4, 4)
x1

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]]])

In [31]:
col1 = im2col(x1, 3, 3, stride=1, pad=0)

In [32]:
col1.shape

(4, 27)

In [33]:
col1

array([[ 0.,  1.,  2.,  4.,  5.,  6.,  8.,  9., 10., 16., 17., 18., 20.,
        21., 22., 24., 25., 26., 32., 33., 34., 36., 37., 38., 40., 41.,
        42.],
       [ 1.,  2.,  3.,  5.,  6.,  7.,  9., 10., 11., 17., 18., 19., 21.,
        22., 23., 25., 26., 27., 33., 34., 35., 37., 38., 39., 41., 42.,
        43.],
       [ 4.,  5.,  6.,  8.,  9., 10., 12., 13., 14., 20., 21., 22., 24.,
        25., 26., 28., 29., 30., 36., 37., 38., 40., 41., 42., 44., 45.,
        46.],
       [ 5.,  6.,  7.,  9., 10., 11., 13., 14., 15., 21., 22., 23., 25.,
        26., 27., 29., 30., 31., 37., 38., 39., 41., 42., 43., 45., 46.,
        47.]])